version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-west-1 --no-include-email)
      - REPOSITORY_URI=999936222461.dkr.ecr.us-west-1.amazonaws.com/teste123
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
      - echo Restore started on `date`
      - dotnet restore Eccosys.Workflow.Api/Eccosys.Workflow.Api.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'
